# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "web" do |web|
    web.vm.box = "gortazar/ingweb-comp-nube-64-java"
    web.vm.network "private_network", ip: "192.168.33.20"
  end

  config.vm.define "db" do |db|
    db.vm.box = "gortazar/ingweb-comp-nube-64-mongodb"
    db.vm.network "private_network", ip: "192.168.33.21"
    db.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "350"]
    end
  end

  config.vm.synced_folder "../data", "/opt"

end
