# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "web1" do |web|
    web.vm.box = "gortazar/ingweb-comp-nube-64-java"
    web.vm.network "private_network", ip: "192.168.33.31"
  end

  config.vm.define "web2" do |web|
    web.vm.box = "gortazar/ingweb-comp-nube-64-java"
    web.vm.network "private_network", ip: "192.168.33.32"
  end

  config.vm.define "db" do |db|
    db.vm.box = "gortazar/ingweb-comp-nube-64-mongodb"
    db.vm.network "private_network", ip: "192.168.33.33"
    db.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "350"]
    end
  end
  
  config.vm.define "lb" do |lb|
    lb.vm.box = "gortazar/ingweb-comp-nube-32-haproxy"
    lb.vm.network "private_network", ip: "192.168.33.30"
  end
  
  config.vm.synced_folder "../data", "/opt"

end
